config/routes.rb
Prtfl::Application.routes.draw do
  get "remote_accounts/index"

  # ADMIN
  match "/admin" => "admin#index"
  resources :beta_codes

  # USERS & SESSIONS
  resources :users
  resources :user_sessions
  match "/login"  => "user_sessions#new",     :as => :login
  match "/logout" => "user_sessions#destroy", :as => :logout
  match "/signup" => "users#new"

  resources :forgotten_passwords, :only => [:create, :edit, :update]
  match "/forgotten_passwords" => "forgotten_passwords#new", :as => :reset_password

  # HOME
  root :to => "home#index"

  # PORTFOLIO
  resources :portfolios do
    post "order_categories",        :on => :collection
    get  "not_setup",               :on => :member
  end

  match "/stats" => "stats#index", :as => :stats

  resources :categories do
    post "order_photos",  :on => :member
    post "reset",         :on => :member
    post "refresh",       :on => :member
    get  "fetch_form",    :on => :collection
  end

  resources :remote_accounts do
    get "expired", :on => :member
  end

  resources :oauth do
    get "instagram_connect",  :on => :collection
    get "instagram_callback", :on => :collection
    get "facebook_callback",  :on => :collection
  end

  resources :future_users do
    get "handle", :on => :member
  end

  resources :photos

  # ADDITIONAL PAGES
  match "/faq"      => "faq#index",       :as => :faq
  match "/terms"    => "home#terms",      :as => :terms
  match "/contact"  => "home#contact",    :as => :contact
  match "/how_to/themes" => "faq#themes", :as => :themes_tutorial

  # FRONT
  get "/:slug/about"            => "front#about",       :as => :about
  get "/:slug/most_recent"      => "front#most_recent", :as => :most_recent
  get "/:slug(/:category_slug)" => "front#showcase",    :as => :showcase
  get "/:slug/:category_slug/:photo_id" => "front#single_photo", :as => :single_photo
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  skip_before_filter :find_current_portfolio
  skip_before_filter :ensure_portfolio_setup
  before_filter :find_front_portfolio
  before_filter :find_category, :except => [:about, :most_recent]
  before_filter :setup_theme_preview

  def showcase
    @category.update_stats unless (current_user and current_user.portfolio.id == @portfolio.id) or @category.nil?
  end

  def single_photo
    @photo = @category.photos.find(params[:photo_id])
    @photo.update_stats unless (current_user and current_user.portfolio.id == @portfolio.id) or @photo.nil?
  end

  def about
    redirect_to root_path unless @portfolio.about_page
  end

  def most_recent
    @photos = Photo.where(["category_id IN (?)", @portfolio.categories.map(&:id)]).limited.activated.ordered_by_date
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  private

  def find_category
    @category = params[:category_slug].blank? ? @portfolio.categories.first : Category.find_by_slug(params[:category_slug])
  end

  def find_front_portfolio
    @portfolio = Portfolio.find_by_slug(params[:slug])
  end

  def setup_theme_preview
    @portfolio.theme_id = params[:theme_id] if params[:theme_id]
  end

end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/front/_nav.html.haml
%nav
  - @portfolio.categories.each_with_index do |category, i|
    .nav-link-wrapper{:class => ((!@category.nil? and @category.id == category.id) ? " selected " : "") + "category-order-#{i}"}
      = link_to category.title, showcase_path(:slug => @portfolio.slug, :category_slug => category.slug)

  - if @portfolio.recent_page
    .nav-link-wrapper#recent{:class => (controller.action_name == "most_recent" ? "selected" : "")}
      = link_to "Most Recent", most_recent_path(:slug => @portfolio.slug)

  - if @portfolio.about_page
    .nav-link-wrapper#about{:class => (controller.action_name == "about" ? "selected" : "")}
      = link_to "About", about_path(:slug => @portfolio.slug)

app/views/front/_photo.html.haml
.photo{:id => "photo-#{photo.id}", :class => "photo-order-#{i} #{cycle("photo-order-even", "photo-order-odd")}"}
  .image-wrapper
    %a.img-wrapper-link{:href => single_photo_path(:slug => @portfolio.slug, :category_slug => photo.category.slug, :photo_id => photo.id)}
      = image_tag photo.large_photo_url
  - unless photo.title.blank? && photo.description.blank?
    .description-wrapper
      - unless photo.title.blank?
        %h3= photo.title
      - unless photo.description.blank?
        %p= photo.description

app/views/front/_photo.rss.erb
<![CDATA[
  <a class="img-wrapper-link" href="<%= single_photo_path(:slug => @portfolio.slug, :category_slug => photo.category.slug, :photo_id => photo.id) %>">
  <%= image_tag photo.large_photo_url %>
  <% unless photo.title.blank? && photo.description.blank? %>
    <div class="description-wrapper">
      <h3> <%= photo.title %></h3>
      <p> <%= photo.description %></p>
    </div>
  <% end %>
]]>

app/views/front/_photos.html.haml
#photos
  - photos.each_with_index do |photo, i|
    = render :partial => "photo", :locals => {:photo => photo, :i => i}

app/views/front/about.html.haml
#about-page
  %h2= @portfolio.title
  %p.about-content= sanitize @portfolio.description.gsub("\n", "<br />"), :tags => %w(br b strong em i)

  - if @portfolio.facebook_share
    :plain
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=112347598870437";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

    .fb-like{"data-href" => "http://ffocused.com/#{@portfolio.slug}", "data-send" => "true", "data-width" => "450", "data-show-faces" => "true"}

app/views/front/most_recent.html.haml
#main-content#most-recent-showcase
  = render :partial => "photos", :locals => {:photos => @photos}

app/views/front/showcase.html.haml
- if @category.nil?
  #error-404
    This category doesn't exist, sorry.

- else
  #main-content#category-showcase
    #category-description
      %h2.name= @category.title
      .description= @category.description

    = render :partial => "photos", :locals => {:photos => @category.photos.activated.ordered.limited}

app/views/front/single_photo.html.haml
#main-content#single-photo-showcase
  #photos
    = render :partial => "photo", :locals => {:photo => @photo, :i => 0}