config/routes.rb
Prtfl::Application.routes.draw do
  get "remote_accounts/index"

  # ADMIN
  match "/admin" => "admin#index"
  resources :beta_codes

  # USERS & SESSIONS
  resources :users
  resources :user_sessions
  match "/login"  => "user_sessions#new",     :as => :login
  match "/logout" => "user_sessions#destroy", :as => :logout
  match "/signup" => "users#new"

  resources :forgotten_passwords, :only => [:create, :edit, :update]
  match "/forgotten_passwords" => "forgotten_passwords#new", :as => :reset_password

  # HOME
  root :to => "home#index"

  # PORTFOLIO
  resources :portfolios do
    post "order_categories",        :on => :collection
    get  "not_setup",               :on => :member
  end

  match "/stats" => "stats#index", :as => :stats

  resources :categories do
    post "order_photos",  :on => :member
    post "reset",         :on => :member
    post "refresh",       :on => :member
    get  "fetch_form",    :on => :collection
  end

  resources :remote_accounts do
    get "expired", :on => :member
  end

  resources :oauth do
    get "instagram_connect",  :on => :collection
    get "instagram_callback", :on => :collection
    get "facebook_callback",  :on => :collection
  end

  resources :future_users do
    get "handle", :on => :member
  end

  resources :photos

  # ADDITIONAL PAGES
  match "/faq"      => "faq#index",       :as => :faq
  match "/terms"    => "home#terms",      :as => :terms
  match "/contact"  => "home#contact",    :as => :contact
  match "/how_to/themes" => "faq#themes", :as => :themes_tutorial

  # FRONT
  get "/:slug/about"            => "front#about",       :as => :about
  get "/:slug/most_recent"      => "front#most_recent", :as => :most_recent
  get "/:slug(/:category_slug)" => "front#showcase",    :as => :showcase
  get "/:slug/:category_slug/:photo_id" => "front#single_photo", :as => :single_photo
end

app/models/beta_code.rb
class BetaCode < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  after_create :set_slug

  belongs_to :portfolio
  has_many :photos, :order => "position ASC"
  belongs_to :remote_account

  validates_uniqueness_of :slug, :scope => :portfolio_id, :if => Proc.new { |category| !category.new_record? }
  validates_presence_of :title
  validates_presence_of :slug, :if => Proc.new { |category| !category.new_record? }

  def set_slug
    if self.slug.blank?
      self.update_attribute :slug, generated_slug
    end
  end

  def reset
    photos.destroy_all
    refresh
  end

  def update_stats
    # TODO: Bench this vs a more SQL approach. This is nice because more readable and uses scopes.
    photos.limited.ordered.activated.each{ |p| p.update_stats }
  end

  def generated_slug
    "#{self.id}-#{self.title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')}"
  end

end

app/models/future_user.rb
class FutureUser < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :category

  validates_uniqueness_of :flickr_id, :scope => :category_id, :if => Proc.new{|p| !p.flickr_id.blank?}
  validates_uniqueness_of :facebook_photo_id, :scope => :category_id, :if => Proc.new{|p| !p.facebook_photo_id.blank?}

  scope :activated, :conditions => {:deleted => false}
  scope :limited,   :limit => 16
  scope :ordered,   :order => "position DESC"
  scope :printed,   :conditions => "prints > 0", :order => "prints DESC"
  scope :ordered_by_date, :order => "created_at DESC"

  def mark_as_destroyed
    update_attribute(:deleted, true)
  end

  def update_stats
    update_attribute(:prints, (prints + 1))
  end

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  before_validation :set_slug, :set_default_css

  validates_uniqueness_of :slug
  validates_presence_of :slug
  validates_exclusion_of :slug, :in => RESERVED_SLUGS

  belongs_to :user

  has_many :remote_accounts, :dependent => :destroy
  has_many :categories, :order => "position ASC", :dependent => :destroy
  has_many :photos, :through => :categories

  def set_default_css
    self.theme_id = 1 if self.new_record?
  end

  def set_slug
    self.slug = user.login if self.new_record?
  end

  def theme
    THEMES[theme_id]
  end

  def setup?
    !remote_accounts.empty?
  end

  def contextual_photo(category=nil)
    if category
      photo = category.photos.first
    elsif categories.empty?
      photo = nil
    else
      photo = categories.first.photos.first
    end
    photo
  end

end

app/models/remote_account.rb
class RemoteAccount < ActiveRecord::Base
  belongs_to :portfolio
  has_many :categories, :dependent => :destroy

  AVAILABLE_ACCOUNTS = ["flickr", "facebook", "instagram"]
  AVAILABLE_SUBCLASSES = ["RemoteAccount::Flickr", "RemoteAccount::Facebook", "RemoteAccount::InstagramAccount"]

  def class_name
    self.class.to_s.demodulize.downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.perishable_token_valid_for = 1.day
  end

  attr_protected :is_admin

  has_one :portfolio, :dependent => :destroy
  has_many :themes

  validate :check_beta_code, :on => :create

  after_create :setup_portfolio
  after_create :burn_beta_code

  validates_exclusion_of :login, :in => RESERVED_SLUGS

  def burn_beta_code
    code = BetaCode.where(:code => self.beta_code, :used => false).first
    code.update_attributes(:used => true)
  end

  def check_beta_code
    code = BetaCode.where(:code => self.beta_code, :used => false).first
    self.errors.add(:beta_code, I18n.t("users.check_beta_code.invalid")) if code.nil?
  end

  def setup_portfolio
    Portfolio.create!(:title => "#{login}'s Portfolio", 
                      :description => "This is my portfolio using ffocused, it's awesome.", 
                      :user_id => id, :slug => login)
  end

  def self.find_by_login_or_email(login)
     find_by_login(login) || find_by_email(login)
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_login_or_email
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "back"
  before_filter :ensure_admin

  def index
    @users = User.all
    @beta_codes = BetaCode.all
    @future_users = FutureUser.all
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  layout "back"

  def themes
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :find_current_portfolio

  def index
  end

  def contact
  end

  def terms
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beta_coupons_helper.rb
module BetaCouponsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/admin/index.html.haml
%h2 Users
%table#users
  %tr
    %th ID
    %th Email
    %th Beta Code
    %th Title
    %th Cats/RA
    %th Link

  - @users.each do |user|
    %tr
      %td= user.id
      %td= user.email
      %td= user.beta_code
      %td= user.portfolio.title
      %td= "#{user.portfolio.categories.count} / #{user.portfolio.remote_accounts.count}"
      %td= link_to user.portfolio.slug, showcase_path(:slug => user.portfolio.slug)

%h2 Future Users
%table#future-users
  %tr
    %th ID
    %th Email
    %th Handled?
    %th
  - @future_users.each do |future_user|
    %tr
      %td= future_user.id
      %td= future_user.email
      %td{:style => (future_user.handled ? "color:green" : "color:red")}
        = future_user.handled ? "Handled" : "Not Handled"
      %td
        = link_to "Handle Now", handle_future_user_path(future_user)

%h2 Beta Codes
= form_for BetaCode.new do |f|
  = f.label :code
  = f.text_field :code
  = f.submit

%table#beta-codes
  %tr
    %th ID
    %th Code
    %th Used?

  - @beta_codes.each do |beta_code|
    %tr
      %td= beta_code.id
      %td= beta_code.code
      %td{:style => (beta_code.used ? "color:red" : "color:green")}
        = beta_code.used ? "Used" : "Not Used"

app/views/shared/_errors.html.haml
- unless flash.nil? or flash[:notice].blank? or flash[:notice][:title].blank? or flash[:notice][:text].blank?
  :javascript
    $(function(){
      startGritter("#{escape_javascript flash[:notice][:title]}", "#{escape_javascript flash[:notice][:text]}");
    });
    
- unless flash.nil? or flash[:error].blank? or flash[:error][:title].blank? or flash[:error][:text].blank?
  :javascript
    $(function(){
      startGritter("#{escape_javascript flash[:error][:title]}", "#{escape_javascript flash[:error][:text]}");
    });

app/views/shared/_google_analytics.html.haml
- # TODO: Extract for easier integration by other developers
- code = GOOGLE_ANALYTICS if local_assigns[:code].nil?

:plain
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '#{code}']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

app/views/shared/_nav.html.haml
%nav
  .wrapper
    .first
    = link_to t("back.nav.home"), portfolio_path(@current_portfolio), :class => ((controller.controller_name == "portfolios" and controller.action_name == "show")? "selected" : "")

    = link_to t("back.nav.remote_accounts"), remote_accounts_path, :class => ((controller.controller_name == "remote_accounts")? "selected" : "")

    = link_to t("back.nav.categories"), categories_path, :class => ((controller.controller_name == "categories")? "selected" : "")

    = link_to t("back.nav.stats"), stats_path, :class => ((controller.controller_name == "stats")? "selected" : "")

    = link_to t("back.nav.theme"), edit_portfolio_path(@current_portfolio, :type => "theme"), :class => ((controller.controller_name == "portfolios" and controller.action_name == "edit" and params[:type] == "theme")? "selected" : "")

    = link_to t("back.nav.settings"), edit_portfolio_path(@current_portfolio, :type => "settings"), :class => ((controller.controller_name == "portfolios" and controller.action_name == "edit" and params[:type] == "settings")? "selected" : "")

    - if current_user.is_admin?
      = link_to t("back.nav.admin"), "/admin", :class => ((controller.controller_name == "admin")? "selected" : "")

    .last