config/routes.rb
Prtfl::Application.routes.draw do
  get "remote_accounts/index"

  # ADMIN
  match "/admin" => "admin#index"
  resources :beta_codes

  # USERS & SESSIONS
  resources :users
  resources :user_sessions
  match "/login"  => "user_sessions#new",     :as => :login
  match "/logout" => "user_sessions#destroy", :as => :logout
  match "/signup" => "users#new"

  resources :forgotten_passwords, :only => [:create, :edit, :update]
  match "/forgotten_passwords" => "forgotten_passwords#new", :as => :reset_password

  # HOME
  root :to => "home#index"

  # PORTFOLIO
  resources :portfolios do
    post "order_categories",        :on => :collection
    get  "not_setup",               :on => :member
  end

  match "/stats" => "stats#index", :as => :stats

  resources :categories do
    post "order_photos",  :on => :member
    post "reset",         :on => :member
    post "refresh",       :on => :member
    get  "fetch_form",    :on => :collection
  end

  resources :remote_accounts do
    get "expired", :on => :member
  end

  resources :oauth do
    get "instagram_connect",  :on => :collection
    get "instagram_callback", :on => :collection
    get "facebook_callback",  :on => :collection
  end

  resources :future_users do
    get "handle", :on => :member
  end

  resources :photos

  # ADDITIONAL PAGES
  match "/faq"      => "faq#index",       :as => :faq
  match "/terms"    => "home#terms",      :as => :terms
  match "/contact"  => "home#contact",    :as => :contact
  match "/how_to/themes" => "faq#themes", :as => :themes_tutorial

  # FRONT
  get "/:slug/about"            => "front#about",       :as => :about
  get "/:slug/most_recent"      => "front#most_recent", :as => :most_recent
  get "/:slug(/:category_slug)" => "front#showcase",    :as => :showcase
  get "/:slug/:category_slug/:photo_id" => "front#single_photo", :as => :single_photo
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  before_validation :set_slug, :set_default_css

  validates_uniqueness_of :slug
  validates_presence_of :slug
  validates_exclusion_of :slug, :in => RESERVED_SLUGS

  belongs_to :user

  has_many :remote_accounts, :dependent => :destroy
  has_many :categories, :order => "position ASC", :dependent => :destroy
  has_many :photos, :through => :categories

  def set_default_css
    self.theme_id = 1 if self.new_record?
  end

  def set_slug
    self.slug = user.login if self.new_record?
  end

  def theme
    THEMES[theme_id]
  end

  def setup?
    !remote_accounts.empty?
  end

  def contextual_photo(category=nil)
    if category
      photo = category.photos.first
    elsif categories.empty?
      photo = nil
    else
      photo = categories.first.photos.first
    end
    photo
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "back"

  skip_before_filter :ensure_portfolio_setup, :only => [:not_setup]

  def not_setup
  end

  def order_categories
    params[:item_ids].each_with_index do |item_id, i|
      @current_portfolio.categories.find(item_id).update_attribute(:position, i)
    end
    render :nothing => true
  end

  def edit
  end

  def show
  end

  def update
    if @current_portfolio.update_attributes(params[:portfolio])
      flash[:notice] = {:title =>t("success"), :text => t("portfolios.update.notice_text")}
    else
      flash[:error] = {:title =>t("error"), :text => @current_portfolio.errors.full_messages.join(", ")}
    end
    redirect_to portfolio_path(@current_portfolio)
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.haml
= f.label :title
= f.text_field :title

= f.label :description
= f.text_area :description

= f.label :about_page
= f.check_box :about_page

- unless simple
  = f.label :recent_page
  = f.check_box :recent_page

  = f.label :slug
  = f.text_field :slug

  = f.label :footer
  = f.text_area :footer

  = f.label :google_analytics_code
  = f.text_field :google_analytics_code

  = f.label :facebook_share
  = f.check_box :facebook_share

app/views/portfolios/_theme.html.haml
= f.hidden_field :theme_id

#theme-type-picker
  = link_to t("portfolios.edit.theme.use_editor"), "#", :id => "use-css-editor", :class => (@current_portfolio.theme_id.blank? ? "selected" : "")
  = link_to t("portfolios.edit.theme.use_theme"), "#", :id => "use-theme", :class => (@current_portfolio.theme_id.blank? ? "" : "selected")


#css-editor{:style => (@current_portfolio.theme_id.blank? ? "" : "display:none;")}
  = f.label :css
  = f.text_area :css, {:style => "height:300px; width:100%;"}
  .sidenote= raw t("portfolios.edit.theme.creative")
  .sidenote= link_to t("portfolios.edit.theme.how_to_themes"), themes_tutorial_path

#all-themes{:style => (@current_portfolio.theme_id.blank? ? "display:none;" : "")}
  - i = 0
  - THEMES.each do |k, v|
    - if i == 0
      .clearfix
    .theme{:class => (@current_portfolio.theme_id == k ? "selected" : ""), :rel => k}
      .image= image_tag "themes/#{v[:code]}.jpg"
      .info
        %h5
          = v[:title]
          = raw t("by", :name => v[:user])
        .optimized= t(".optimized_for", :remote_accounts => v[:remote_accounts].join(", "))
        - used_by = Portfolio.all(:conditions => {:theme_id => k}, :limit => 3)
        .used
          = t(".used_by")
          = raw used_by.map{|p| link_to(p.title[0..15], showcase_path(:slug => p.slug)) }.join(", ")
        .preview
          = link_to t(".preview"), showcase_path(:slug => @current_portfolio.slug, :theme_id => k), :target => "_blank"
    - i += 1

  %p= link_to t("portfolios.edit.theme.themes_tutorial"), themes_tutorial_path

app/views/portfolios/edit.html.haml
%h2= t("portfolios.edit.#{params[:type]}.title")

- form_for @current_portfolio do |f|
  - if params[:type] == "settings"
    = render :partial => "form", :locals => {:f => f, :simple => false}

  - if params[:type] == "theme"
    = render :partial => "theme", :locals => {:f => f}

  .submit-wrapper
    = f.submit t("portfolios.show.setup_button")

app/views/portfolios/not_setup.html.haml
%h2= t("portfolios.show.get_started")

%p= raw t("portfolios.show.not_setup")
= render :partial => "/remote_accounts/new_forms"

app/views/portfolios/show.html.haml
%h2= t("portfolios.show.welcome")
- if @current_portfolio.remote_accounts.size > 1
  %p= raw t("portfolios.show.setup_ok_advanced")
- else
  %p= raw t("portfolios.show.setup_ok",
          :name => @current_portfolio.remote_accounts.last.remote_user_name,
          :service => @current_portfolio.remote_accounts.last.class_name.capitalize)

- if @current_portfolio.categories.size < 2 or (@current_portfolio.css.blank? and @current_portfolio.theme_id.blank?)
  %h3= t("portfolios.show.left_to_do.title")
  %p= t("portfolios.show.left_to_do.intro")

  #todos
    .todo{:class => @current_portfolio.categories.empty? ? "" : "ticked"}
      = link_to t("portfolios.show.left_to_do.category.link"), categories_path
      = t("portfolios.show.left_to_do.category.text")

    .todo{:class => (@current_portfolio.css.blank? and @current_portfolio.theme_id.blank?) ? "" : "ticked"}
      = link_to t("portfolios.show.left_to_do.theme.link"), edit_portfolio_path(@current_portfolio, :type => "theme")
      = t("portfolios.show.left_to_do.theme.text")

    .todo{:class =>  @current_portfolio.categories.size < 2 ? "" : "ticked"}
      = t("portfolios.show.left_to_do.other_category")