config/routes.rb
Prtfl::Application.routes.draw do
  get "remote_accounts/index"

  # ADMIN
  match "/admin" => "admin#index"
  resources :beta_codes

  # USERS & SESSIONS
  resources :users
  resources :user_sessions
  match "/login"  => "user_sessions#new",     :as => :login
  match "/logout" => "user_sessions#destroy", :as => :logout
  match "/signup" => "users#new"

  resources :forgotten_passwords, :only => [:create, :edit, :update]
  match "/forgotten_passwords" => "forgotten_passwords#new", :as => :reset_password

  # HOME
  root :to => "home#index"

  # PORTFOLIO
  resources :portfolios do
    post "order_categories",        :on => :collection
    get  "not_setup",               :on => :member
  end

  match "/stats" => "stats#index", :as => :stats

  resources :categories do
    post "order_photos",  :on => :member
    post "reset",         :on => :member
    post "refresh",       :on => :member
    get  "fetch_form",    :on => :collection
  end

  resources :remote_accounts do
    get "expired", :on => :member
  end

  resources :oauth do
    get "instagram_connect",  :on => :collection
    get "instagram_callback", :on => :collection
    get "facebook_callback",  :on => :collection
  end

  resources :future_users do
    get "handle", :on => :member
  end

  resources :photos

  # ADDITIONAL PAGES
  match "/faq"      => "faq#index",       :as => :faq
  match "/terms"    => "home#terms",      :as => :terms
  match "/contact"  => "home#contact",    :as => :contact
  match "/how_to/themes" => "faq#themes", :as => :themes_tutorial

  # FRONT
  get "/:slug/about"            => "front#about",       :as => :about
  get "/:slug/most_recent"      => "front#most_recent", :as => :most_recent
  get "/:slug(/:category_slug)" => "front#showcase",    :as => :showcase
  get "/:slug/:category_slug/:photo_id" => "front#single_photo", :as => :single_photo
end

app/models/category.rb
class Category < ActiveRecord::Base
  after_create :set_slug

  belongs_to :portfolio
  has_many :photos, :order => "position ASC"
  belongs_to :remote_account

  validates_uniqueness_of :slug, :scope => :portfolio_id, :if => Proc.new { |category| !category.new_record? }
  validates_presence_of :title
  validates_presence_of :slug, :if => Proc.new { |category| !category.new_record? }

  def set_slug
    if self.slug.blank?
      self.update_attribute :slug, generated_slug
    end
  end

  def reset
    photos.destroy_all
    refresh
  end

  def update_stats
    # TODO: Bench this vs a more SQL approach. This is nice because more readable and uses scopes.
    photos.limited.ordered.activated.each{ |p| p.update_stats }
  end

  def generated_slug
    "#{self.id}-#{self.title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')}"
  end

end

app/models/category/facebook.rb
class Category::Facebook < Category
  after_create :set_photos_from_facebook

  def refresh
    set_photos_from_facebook
  end

  def set_photos_from_facebook
    graph = Koala::Facebook::GraphAPI.new(remote_account.access_token)
    res = graph.get_connections(facebook_album_id, "photos", :fields => "id,name,images", :limit => 200)
    res.each_with_index do |photo, i|
      Photo.create(
        :position => i,
        :facebook_photo_id => photo["id"],
        :large_photo_url => photo["images"].first["source"],
        :small_photo_url => photo["images"].last["source"],
        :category_id => self.id,
        :description => photo["name"],
        :title => (photo["name"].blank? ? "" : photo["name"][0..50])
      )
    end
  end

end

app/models/category/flickr.rb
class Category::Flickr < Category
  after_create :set_photos_from_flickr

  def refresh
    set_photos_from_flickr
  end

  def set_photos_from_flickr
    res = Fetchers::Flickr::Request.call_method("photosets.getPhotos", {:photoset_id => flickr_set_id, :per_page => "100"})
    map_photos(res["photoset"]["photo"])
  end

  def map_photos(photos)
    photos.each_with_index do |photo, i|
      flickr_photo_id = photo["id"]
      large_photo_url, small_photo_url = find_photo_sizes(flickr_photo_id)
      Photo.create(
        :position => i,
        :flickr_photo_id => flickr_photo_id, #FIXME: dupe with flickr_id?
        :large_photo_url => large_photo_url,
        :small_photo_url => small_photo_url,
        :flickr_id => photo["id"],
        :category_id => self.id,
        :title => photo["title"]
      )
    end
  end

  def find_photo_sizes(flickr_photo_id)
    sizes = Fetchers::Flickr::Request.call_method("photos.getSizes", {:photo_id => flickr_photo_id})
    small_photo_url = sizes["sizes"]["size"].detect{|k,v| k["label"] == "Square"}["source"]
    large_data = sizes["sizes"]["size"].detect{|k,v| k["label"] == "Large"}
    large_data = sizes["sizes"]["size"].detect{|k,v| k["label"] == "Medium"} if large_data.nil?
    large_photo_url = large_data["source"]
    return large_photo_url, small_photo_url
  end
end

app/models/category/instagram.rb
class Category::Instagram < Category
  after_create :set_photos_from_instagram

  def refresh
    set_photos_from_instagram
  end

  def set_photos_from_instagram
    remote_account.photos.each_with_index do |photo, i|
      Photo.create(
        :position => i,
        :large_photo_url => photo["images"]["standard_resolution"]["url"],
        :small_photo_url => photo["images"]["thumbnail"]["url"],
        :category_id => self.id,
        :description => photo["filter"],
        :title => Time.at(photo["created_time"].to_i).strftime("%m/%d/%Y")
      )
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'back'

  before_filter :find_category, :only => [:edit, :destroy, :update, :refresh, :reset]
  before_filter :use_valid_remote_account, :only => [:refresh, :reset]

  def index
    @categories = @current_portfolio.categories
    @remote_accounts = @current_portfolio.remote_accounts
  end

  def edit
  end

  def fetch_form
    remote_account = @current_portfolio.remote_accounts.find(params[:remote_account_id])
    unless remote_account.still_valid?
      render :partial => "/categories/forms/expired", :locals => {:remote_account => remote_account}
    else
      render :partial => "/categories/forms/#{remote_account.class_name}", :locals => {:remote_account => remote_account}
    end
  end

  def update
    # FIXME: This is terrible
    params[:category] = params[:category_instagram] if params[:category].blank?
    params[:category] = params[:category_facebook] if params[:category].blank?
    params[:category] = params[:category_flickr] if params[:category].blank?

    if @category.update_attributes(
                    :title => params[:category][:title],
                    :slug => params[:category][:slug],
                    :description => params[:category][:description]
                    )
      flash[:notice] = {:title => t("categories.update.success_title"), :text => t("categories.update.success_text")}
    else
      flash[:error] = {:title => t("categories.update.error_title"), :text => t("categories.update.error_text")}
    end
    redirect_to edit_category_path(@category)
  end

  def destroy
    @category.destroy
    render :nothing => true
  end

  def order_photos
    @category = @current_portfolio.categories.find(params[:id])
    params[:item_ids].each_with_index do |item_id, i|
      @category.photos.find(item_id).update_attribute(:position, i)
    end
    render :nothing => true
  end

  def reset
    @category.reset
    flash[:notice] = {:title => t("categories.reset.title"), :text => t("categories.reset.text")}
    redirect_to category_path(@category)
  end

  def refresh
    @category.refresh
    flash[:notice] = {:title => t("categories.refresh.title"), :text => t("categories.refresh.text")}
    redirect_to category_path(@category)
  end

  def create
    @category = params[:type].constantize.new(params[:category].merge(:portfolio_id => @current_portfolio.id))
    use_valid_remote_account
    if @category.save
      flash[:notice] = {:title => t("categories.create.success_title"), :text => t("categories.create.success_text")}
      redirect_to category_path(@category)
    else
      flash[:error] = {:title => t("categories.create.error_title"), :text => t("categories.create.error_text", :errors => @category.errors.full_messages.join(", "))}
      redirect_to categories_path
    end
  end

  def show
    @category = @current_portfolio.categories.find(params[:id])
  end

  protected

  def find_category
    @category = @current_portfolio.categories.find(params[:id])
  end

  def use_valid_remote_account
    redirect_to expired_remote_account_path(@category.remote_account) unless @category.remote_account.still_valid?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_new.html.haml
#new-category{:style => (@categories.empty? ? "" : "display:none")}
  #all-get-category-form
    %h4= t("categories.index.choose_account")
    - @remote_accounts.each do |account|
      = link_to account.remote_user_name, fetch_form_categories_path(:remote_account_id => account.id), :class => "get-new-category-form account-entry-#{account.class_name}"

  #new-category-form

app/views/categories/edit.html.haml
%h2= t("categories.edit.title", :name => @category.title)
- form_for @category, :url => category_path(@category) do |f|
  = f.label :title
  = f.text_field :title

  = f.label :description
  = f.text_area :description

  = f.label :slug
  = f.text_field :slug

  .submit-wrapper
    = f.submit

app/views/categories/index.html.haml
%h2= t("categories.index.all_categories")

%p.help=raw t("categories.index.blurb")

- if @categories.empty?
  %p= t("categories.index.first_time")
- else
  %p= link_to t("categories.index.new_category"), "#", :class => "show-rel hide-self plus-button", :rel => "#new-category"

= render :partial => "new"

- unless @categories.empty?
  %ul#categories.sortable{:rel => order_categories_portfolios_path}
    - @categories.each do |category|
      %li.category{:rel => category.id, :id => "entry-#{category.id}"}
        - unless category.photos.empty?
          = image_tag category.photos.find(:first).small_photo_url

        .title
          = link_to category.title, category_path(category)
          #{category.photos.count} Photos
          #actions
            = link_to "Delete", category_path(category), :class => "delete action", :rel => "#entry-#{category.id}"
            = link_to "Edit", edit_category_path(category), :class => "edit action"

app/views/categories/show.html.haml
%h2= t("categories.show.title", :title => @category.title)
= link_to t("categories.show.back"), categories_path, :class => "back-link"
%p= t("categories.show.blurb")

%ul#photos.sortable{:rel => order_photos_category_path(@category)}
  - @category.photos.activated.each do |photo|
    %li.photo{:rel => photo.id, :id => "entry-#{photo.id}"}
      = image_tag photo.small_photo_url
      .title
        = photo.title
        #actions
          = t(".prints", :count => photo.prints)
          = link_to t("edit"), edit_photo_path(photo, :category_id => @category.id), :class => "action"
          = link_to t("delete"), photo_path(photo, :category_id => @category.id), :class => "delete action", :rel => "#entry-#{photo.id}"

.bottom-reset
  = t("categories.show.refresh")
  = form_tag refresh_category_path(@category), :id => "reset-category" do
    = submit_tag t("categories.show.refresh_button")

.bottom-reset
  = t("categories.show.reset")
  = form_tag reset_category_path(@category), :id => "reset-category" do
    = submit_tag t("categories.show.reset_button")